spring.application.name=QuickBlog

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# SERVER
server.port=${PORT:8080}
server.error.include-message=never

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# FILE UPLOAD
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# GEMINI AI
gemini.api-key=${GEMINI_API_KEY}
gemini.model=gemini-3.1-flash-lite